### ISSUE TITLE
Build fails if C:\temp does not exist

### ISSUE THREAD

**Issue by nref** [kaby76/PiggySimple#1]
Title says it

**Comment by hulaomr** [comment]
Hi, 
Nice project.
I follow the suggested instructions (using sample project) and I got these messages in VS2019. Any advices appreciated.
Thanks

`2>------ Rebuild All started: Project: Csharp, Configuration: Debug Any CPU ------
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error: Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\temp\generated_templates.cs'.
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.StreamWriter..ctor(String path)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at System.IO.File.WriteAllText(String path, String contents)
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at PiggyGenerator.OutputEngine.GenerateAndCompileTemplates() in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\OutputEngine.cs:line 267
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at PiggyGenerator.OutputEngine.Run(Boolean grep_only) in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\OutputEngine.cs:line 639
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at PiggyGenerator.Piggy.RunTool(String ast_file, String spec_file, Boolean keep_file, String expression, String template_directory, String output_file) in C:\Users\Kenne\Documents\Piggy3\PiggyGenerator\Piggy.cs:line 88
2>C:\Users\...\.nuget\packages\piggy\1.0.14\build\Piggy.targets(64,5): error : Unknown build error:    at ConsoleApp1.Program.Main(String[] args) in C:\Users\Kenne\Documents\Piggy3\PiggyTool\Program.cs:line 64
2>Done building project "Csharp.csproj" -- FAILED.`

**Comment by nref** [comment]
Just create the folder C:/temp.

**Comment by hulaomr** [comment]
Dear @slater1,
Thanks for your feedback.
I created the folder and everything looks OK now!
Regards
